/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mercadogod.screens;

import java.sql.*;
import br.com.mercadogod.dal.ConnectionModule;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Junior
 */
public class CliScreen extends javax.swing.JInternalFrame {
    private Connection connection;
    private PreparedStatement pst;
    private ResultSet rs;
    private DecimalFormat df = new DecimalFormat("###,###.##");
    /**
     * Creates new form CliScreen
     */
    public CliScreen() {
        initComponents();
        connection = ConnectionModule.connection();
        atualizar_table();
        //update_values();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtSearchCli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cliTable = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        txtCliName = new javax.swing.JTextField();
        lblNomeCli = new javax.swing.JLabel();
        txtClid = new javax.swing.JTextField();
        lblIDCli = new javax.swing.JLabel();
        txtCliTele = new javax.swing.JTextField();
        lblFoneCli = new javax.swing.JLabel();
        lblMsgCli = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCliMsg = new javax.swing.JTextPane();
        jPanel10 = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        saleTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableTotPrice = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtIdCliCont = new javax.swing.JTextField();
        btnFinalCont = new javax.swing.JButton();
        txtNameCont = new javax.swing.JTextField();
        txtValPagar = new javax.swing.JTextField();
        btnEditCont = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMasterCli = new javax.swing.JMenu();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));

        txtSearchCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchCliKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Pesquisar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(txtSearchCli, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchCli, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));

        cliTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        cliTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cliTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(cliTable);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Área do Cliente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Century Gothic", 1, 18))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel11.add(txtCliName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 290, -1));

        lblNomeCli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNomeCli.setText("Nome");
        jPanel11.add(lblNomeCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        txtClid.setEditable(false);
        txtClid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClidActionPerformed(evt);
            }
        });
        jPanel11.add(txtClid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 52, 30));

        lblIDCli.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblIDCli.setText("ID");
        jPanel11.add(lblIDCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanel11.add(txtCliTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 290, -1));

        lblFoneCli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblFoneCli.setText("Telefone");
        jPanel11.add(lblFoneCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        lblMsgCli.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblMsgCli.setText("Mensagem");
        jPanel11.add(lblMsgCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jScrollPane4.setViewportView(txtCliMsg);

        jPanel11.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 290, 40));

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(51, 51, 51)));

        btnCreate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCreate.setText("CRIAR");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnEdit.setText("EDITAR");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnDelete.setText("DELETAR");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(btnDelete)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCreate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Devedores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 522));

        jPanel2.setBackground(new java.awt.Color(145, 145, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null), "Vendas a clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        saleTable.setBackground(new java.awt.Color(204, 204, 204));
        saleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        saleTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(saleTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(145, 145, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 255), null), "Valor Total de Cada Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        tableTotPrice.setBackground(new java.awt.Color(204, 204, 204));
        tableTotPrice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTotPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTotPriceMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableTotPrice);

        jPanel8.setBackground(new java.awt.Color(148, 145, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 255), null), "Manuseio de devedores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Century Gothic", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(150, 145, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), null), "ID CLIENTE", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Century Gothic", 1, 12))); // NOI18N

        txtIdCliCont.setEditable(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtIdCliCont, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtIdCliCont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        btnFinalCont.setText("FINALIZAR CONTA");
        btnFinalCont.setEnabled(false);
        btnFinalCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalContActionPerformed(evt);
            }
        });

        txtNameCont.setEditable(false);

        txtValPagar.setEditable(false);

        btnEditCont.setText("EDITAR CONTA");
        btnEditCont.setEnabled(false);
        btnEditCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditContActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Valor à pagar");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditCont, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalCont))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNameCont, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(txtValPagar)))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNameCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalCont, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditCont, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));

        menuMasterCli.setBackground(new java.awt.Color(0, 0, 0));
        menuMasterCli.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));
        menuMasterCli.setIcon(new javax.swing.ImageIcon("C:\\Users\\Junior\\Desktop\\client.png")); // NOI18N
        menuMasterCli.setText("Cliente");
        menuMasterCli.setEnabled(false);
        menuMasterCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMasterCliActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuMasterCli);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1365, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void menuMasterCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMasterCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuMasterCliActionPerformed

    private void tableTotPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTotPriceMouseClicked
        // TODO add your handling code here:
        fill_table_price();
    }//GEN-LAST:event_tableTotPriceMouseClicked

    private void btnEditContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditContActionPerformed
        // TODO add your handling code here:
        edit_cont();
    }//GEN-LAST:event_btnEditContActionPerformed

    private void btnFinalContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalContActionPerformed
        // TODO add your handling code here:
        final_acc();
    }//GEN-LAST:event_btnFinalContActionPerformed

    private void txtClidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClidActionPerformed

    private void cliTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliTableMouseClicked
        // TODO add your handling code here:
        fill_table_cli();
    }//GEN-LAST:event_cliTableMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        edit_cli();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        delete_cli();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        create_cli();
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtSearchCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchCliKeyReleased
        // TODO add your handling code here:
        search_cli();
    }//GEN-LAST:event_txtSearchCliKeyReleased
    private void atualizar_table(){
        String query_cli = "select idclient as IDCliente,clientname as Nome,clientfone as Telefone, climessage as Mensagem from clitable";
        String query_sale = "select c.idclient as IDCliente, c.clientname as NomeCliente, s.idsale as IDVenda, s.saledate as DataVenda, s.saleprice as PreçoVenda from saletable s join clitable c on s.idclient=c.idclient order by c.idclient";
        String query_dev = "select idclient as ClientID, clientname as NomeCliente, totprice as ValorTotal from clitable";
        try{
            pst = connection.prepareStatement(query_cli);
            rs = pst.executeQuery();
            cliTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            pst = connection.prepareStatement(query_sale);
            rs = pst.executeQuery();
            saleTable.setModel(DbUtils.resultSetToTableModel(rs));
            
            pst = connection.prepareStatement(query_dev);
            rs = pst.executeQuery();
            tableTotPrice.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
            
        }
    }
    /*private void update_values(){
        String queryCount = "select count(*) from clitable";
        String querySum = "select sum(saleprice) from saletable s join clitable c on s.idclient = c.idclient where c.idclient=?";
        String insertQuery = "update clitable set totprice = ? where idclient = ?";
        String queryAttTable = "select idclient as ClientID, clientname as NomeCliente, totprice as ValorTotal from clitable";
        try{
            pst = connection.prepareStatement(queryCount);
            rs = pst.executeQuery();
            if(rs.next()){
                int count = Integer.parseInt(rs.getString(1))+1;
                int linhas=0;
                for(int i=1; i<count; i++){
                    String id = cliTable.getModel().getValueAt(linhas, 0).toString();
                    pst = connection.prepareStatement(querySum);
                    pst.setString(1, id);
                    rs = pst.executeQuery();
                    if(rs.next()){
                        String valorTot = rs.getString(1);
                        if(valorTot==null){
                            
                        } else {
                            pst = connection.prepareStatement(insertQuery);
                            pst.setString(1, valorTot);
                            pst.setString(2, id);
                            int sucesso = pst.executeUpdate();
                            if(sucesso > 0 ){
                                pst = connection.prepareStatement(queryAttTable);
                                rs = pst.executeQuery();
                                tableTotPrice.setModel(DbUtils.resultSetToTableModel(rs));
                            }
                        }
                    }
                    linhas++;
                }
            }
        }catch(SQLException e){
            
        }
    }*/
    private void final_acc(){
        int certeza = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja finalizar essa conta?","Finalizar Conta", JOptionPane.YES_NO_OPTION);
        if(certeza == JOptionPane.YES_OPTION){
            String removeCountQuery = "update clitable set totprice=? where idclient=?";
            try{
                pst = connection.prepareStatement(removeCountQuery);
                pst.setString(1, "0.00");
                pst.setString(2, txtIdCliCont.getText());
                int sucess = pst.executeUpdate();
                if(sucess>0){
                    JOptionPane.showMessageDialog(null, "Conta finalizada com sucesso!");
                    txtIdCliCont.setText(null);
                    txtValPagar.setText(null);
                    txtNameCont.setText(null);
                    btnEditCont.setEnabled(false);
                    btnFinalCont.setEnabled(false);
                    atualizar_table();
                }
            }catch(SQLException e){
                
            }
        }
    }
    private void edit_cont(){
        String edit_query="update clitable set totprice=? where idclient=?";
        int continuar = JOptionPane.showConfirmDialog(null, "Certeza que deseja editar essa conta ?","Editar Conta", JOptionPane.YES_NO_OPTION);
        try{
            if(continuar == JOptionPane.YES_OPTION){
                pst = connection.prepareStatement(edit_query);
                if(txtValPagar.getText().isEmpty()||Double.parseDouble(txtValPagar.getText())<0){
                    txtValPagar.setText("0");
                    pst.setString(1, txtValPagar.getText());
                } else {
                    pst.setString(1, txtValPagar.getText());
                }
                pst.setString(2, txtIdCliCont.getText());
                int sucess = pst.executeUpdate();
                if(sucess>0){
                    JOptionPane.showMessageDialog(null, "Conta atualizada com sucesso!");
                    txtIdCliCont.setText(null);
                    txtValPagar.setText(null);
                    txtNameCont.setText(null);
                    btnEditCont.setEnabled(false);
                    btnFinalCont.setEnabled(false);
                    atualizar_table();
                }
            }
        }catch(SQLException e){
            
        }
    }
    private void fill_table_price(){
        int set = tableTotPrice.getSelectedRow();
            txtIdCliCont.setText(tableTotPrice.getModel().getValueAt(set, 0).toString());
            txtNameCont.setText(tableTotPrice.getModel().getValueAt(set, 1).toString());
            txtValPagar.setText(tableTotPrice.getModel().getValueAt(set, 2).toString().replace(',', '.'));
            txtValPagar.setEditable(true);
            btnEditCont.setEnabled(true);
            btnFinalCont.setEnabled(true);
    }
    private void fill_table_cli(){
        int set = cliTable.getSelectedRow();
        txtClid.setText(cliTable.getModel().getValueAt(set, 0).toString());
        txtCliName.setText(cliTable.getModel().getValueAt(set, 1).toString());
        txtCliTele.setText(cliTable.getModel().getValueAt(set, 2).toString());
        txtCliMsg.setText(cliTable.getModel().getValueAt(set, 3).toString());
        btnCreate.setEnabled(false);
        btnEdit.setEnabled(true);
        btnDelete.setEnabled(true);
    }
    private void create_cli(){
        if(txtCliName.getText().isEmpty()||txtCliTele.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Informe os campos necessários!");
        } else {
            String createCliQuery= "insert into clitable (clientname,clientfone,climessage) values(?,?,?)";
            try{
                pst = connection.prepareStatement(createCliQuery);
                pst.setString(1, txtCliName.getText());
                pst.setString(2, txtCliTele.getText());
                pst.setString(3, txtCliMsg.getText());
                int sucesso = pst.executeUpdate();
                if(sucesso>0){
                    JOptionPane.showMessageDialog(null, "Cliente registrado com sucesso!");
                    txtCliName.setText(null);
                    txtCliTele.setText(null);
                    txtCliMsg.setText(null);
                    atualizar_table();
                }
            } catch(SQLException e) {

            }
        }
    }
    private void edit_cli(){
        String editCliQuery = "Update clitable set clientname=?,clientfone=?,climessage=? where idclient=?";
        int permitir = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja editar este cliente ?", "Editar Cliente", JOptionPane.YES_NO_OPTION);
        if(permitir==JOptionPane.YES_OPTION){
            try{
                pst = connection.prepareStatement(editCliQuery);
                pst.setString(1, txtCliName.getText());
                pst.setString(2, txtCliTele.getText());
                pst.setString(3, txtCliMsg.getText());
                pst.setString(4, txtClid.getText());
                int sucesso = pst.executeUpdate();
                if(sucesso>0){
                    JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso!");
                    txtCliName.setText(null);
                    txtCliTele.setText(null);
                    txtCliMsg.setText(null);
                    txtClid.setText(null);
                    btnEdit.setEnabled(false);
                    btnDelete.setEnabled(false);
                    btnCreate.setEnabled(true);
                    atualizar_table();
                }
            } catch(SQLException e) {

            }
        }
    }
    private void delete_cli(){
        int confirmar = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este cliente ?" ,"Deletar Cliente", JOptionPane.YES_NO_OPTION);
        if(confirmar==JOptionPane.YES_OPTION){
            String deleteCliQuery = "delete from clitable where idclient=?";
            try{
                pst = connection.prepareStatement(deleteCliQuery);
                pst.setString(1, txtClid.getText());
                int sucesso = pst.executeUpdate();
                if(sucesso>0){
                    JOptionPane.showMessageDialog(null, "Cliente removido com sucesso!");
                    txtCliName.setText(null);
                    txtCliTele.setText(null);
                    txtCliMsg.setText(null);
                    txtClid.setText(null);
                    btnEdit.setEnabled(false);
                    btnDelete.setEnabled(false);
                    btnCreate.setEnabled(true);
                    atualizar_table();
                }
            }catch(SQLException e){

            }
        }
    }
    
    private void search_cli(){
        String searchCliQuery="select idclient as IDCliente,clientname as Nome,clientfone as Telefone, climessage as Mensagem from clitable where clientname like ? order by idclient";
        try{
            pst = connection.prepareStatement(searchCliQuery);
            pst.setString(1, txtSearchCli.getText()+"%");
            rs = pst.executeQuery();
            cliTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch(SQLException e){
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditCont;
    private javax.swing.JButton btnFinalCont;
    protected javax.swing.JTable cliTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblFoneCli;
    private javax.swing.JLabel lblIDCli;
    private javax.swing.JLabel lblMsgCli;
    private javax.swing.JLabel lblNomeCli;
    private javax.swing.JMenu menuMasterCli;
    protected javax.swing.JTable saleTable;
    private javax.swing.JTable tableTotPrice;
    private javax.swing.JTextPane txtCliMsg;
    private javax.swing.JTextField txtCliName;
    private javax.swing.JTextField txtCliTele;
    private javax.swing.JTextField txtClid;
    private javax.swing.JTextField txtIdCliCont;
    private javax.swing.JTextField txtNameCont;
    private javax.swing.JTextField txtSearchCli;
    private javax.swing.JTextField txtValPagar;
    // End of variables declaration//GEN-END:variables
}
