/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mercadogod.screens;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Junior
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        btnSell = new javax.swing.JButton();
        btnNewProd = new javax.swing.JButton();
        btnCli = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mercado GOD ");
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desktop.setBackground(new java.awt.Color(142, 198, 247));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1360, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1360, 600));

        btnSell.setBackground(new java.awt.Color(255, 255, 255));
        btnSell.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercadogod/icons/iconfinder_941-32_4619651.png"))); // NOI18N
        btnSell.setText("Venda");
        btnSell.setBorder(null);
        btnSell.setBorderPainted(false);
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });
        getContentPane().add(btnSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 320, 110));

        btnNewProd.setBackground(new java.awt.Color(255, 255, 255));
        btnNewProd.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnNewProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/mercadogod/icons/iconfinder_ic_fiber_new_48px_3669431.png"))); // NOI18N
        btnNewProd.setText("Produto");
        btnNewProd.setBorder(null);
        btnNewProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNewProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewProdActionPerformed(evt);
            }
        });
        getContentPane().add(btnNewProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 320, 110));

        btnCli.setBackground(new java.awt.Color(255, 255, 255));
        btnCli.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnCli.setText("Cliente");
        btnCli.setBorder(null);
        btnCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliActionPerformed(evt);
            }
        });
        getContentPane().add(btnCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 340, 110));

        btnRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        btnRelatorio.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnRelatorio.setText("Relatório");
        btnRelatorio.setBorder(null);
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 380, 110));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed
        // TODO add your handling code here:
        sell();
    }//GEN-LAST:event_btnSellActionPerformed

    private void btnNewProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewProdActionPerformed
        // TODO add your handling code here:
        newProd();
    }//GEN-LAST:event_btnNewProdActionPerformed

    private void btnCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliActionPerformed
        // TODO add your handling code here:
        clients();
    }//GEN-LAST:event_btnCliActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        // TODO add your handling code here:
        reportscreen();
    }//GEN-LAST:event_btnRelatorioActionPerformed
    private void setColor(JPanel panel){
        panel.setBackground(new Color(83,123,253));
    }
    private void resetColor(JPanel panel){
        panel.setBackground(new Color(83,158,248));
    }
    private void sell(){
        SellScreen ss = new SellScreen();
        ss.setVisible(true);
        desktop.add(ss);
    }
    private void newProd(){
        NewProdScreen np = new NewProdScreen();
        np.setVisible(true);
        desktop.add(np);
    }
    private void clients(){
        CliScreen cs = new CliScreen();
        cs.setVisible(true);
        desktop.add(cs);
    }
    private void reportscreen(){
        ReportScreen rs = new ReportScreen();
        rs.setVisible(true);
        desktop.add(rs);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCli;
    private javax.swing.JButton btnNewProd;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnSell;
    private javax.swing.JDesktopPane desktop;
    // End of variables declaration//GEN-END:variables
}
