/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.mercadogod.screens;

import java.sql.*;
import br.com.mercadogod.dal.ConnectionModule;
import java.text.DecimalFormat;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Junior
 */
public class ReportScreen extends javax.swing.JInternalFrame {
    private Connection connection;
    private PreparedStatement pst;
    private ResultSet rs;
    DecimalFormat df = new DecimalFormat("###,###.##");
    
    /**
     * Creates new form ReportScreen
     */
    public ReportScreen() {
        initComponents();
        connection = ConnectionModule.connection();
        report();
        valorTot();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SelledTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtValTot = new javax.swing.JTextField();
        txtValRecCli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValReal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtLucroReal = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 605, 1349, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Itens vendidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SelledTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(SelledTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, 1328, 328));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Valor TOTAL");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 439, -1, 43));
        jPanel2.add(txtValTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 439, 372, 43));
        jPanel2.add(txtValRecCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 389, 372, 43));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Valor a receber(CLIENTES)");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 389, -1, 44));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("VALOR DO LUCRO REAL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 488, -1, 40));
        jPanel2.add(txtValReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 488, 372, 40));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 204, 204), null));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("VALOR DO LUCRO RETIRANDO VALOR DOS PRODUTOS");

        txtLucroReal.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLucroReal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLucroReal, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, -1, 130));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 11, 1340, 560));

        setBounds(0, 0, 1365, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void report(){
        String query = "select s.idvenda as IdVenda, s.selldate as DataV, p.productid as IdProd, p.prodname as Produto, p.prodval as Validade, s.prodmount as Quantidade, p.prodprice as Preço, s.prodlucro as Lucro, p.prodvalue as ValorOrigi,s.prodreal as VendaOrigi from saletabletrue s join prodtable p on s.productid=p.productid order by idvenda;";
        try{
            pst = connection.prepareStatement(query);
            rs = pst.executeQuery();
            SelledTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
            
        }
    }
    private void valorTot(){
        String valRecCli="0";
        String valTot="0";
        String query_valRecCli = "select sum(totprice) from clitable";
        String query_valTot = "select sum(s.prodlucro) as Lucro from saletabletrue s join prodtable p on s.productid=p.productid";
        String query_valRealTot = "select sum(prodlucro)-sum(prodreal) from saletabletrue";
        try{
            pst = connection.prepareStatement(query_valRecCli);
            rs = pst.executeQuery();
            if(rs.next()){
                if(rs.getString(1)==null){
                    txtValRecCli.setText("0.00");
                    valRecCli="0";
                } else {
                    txtValRecCli.setText(rs.getString(1));
                    valRecCli=rs.getString(1);
                }
            }
            
            pst = connection.prepareStatement(query_valTot);
            rs = pst.executeQuery();
            if(rs.next()){
                if(rs.getString(1)==null){
                    txtValTot.setText("0.00");
                    valTot="0";
                } else {
                    txtValTot.setText(rs.getString(1));
                    valTot=rs.getString(1);
                }
            }
            double resultado = Double.parseDouble(valTot)-Double.parseDouble(valRecCli);
            txtValReal.setText(df.format(resultado));
            
            pst = connection.prepareStatement(query_valRealTot);
            rs = pst.executeQuery();
            if(rs.next()){
                if(rs.getString(1)==null){
                    txtLucroReal.setText("0.00");
                } else {
                    double realResult= Double.parseDouble(rs.getString(1))-Double.parseDouble(valRecCli);
                    txtLucroReal.setText(df.format(realResult));
                }
            }
        }catch(SQLException e){
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable SelledTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtLucroReal;
    private javax.swing.JTextField txtValReal;
    private javax.swing.JTextField txtValRecCli;
    private javax.swing.JTextField txtValTot;
    // End of variables declaration//GEN-END:variables
}
